name: Terraform
run-name: ${{ github.actor }} is running pre-commit

on:
  push:
    branches:
      - 13.0
jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
        run:
            shell: bash
            working-directory: terraform

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.8
          tf_actions__subcommand: 'fmt'
          tf_actions_working_dir: './terraform'

      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: '0.14.8'
          tf_actions__subcommand: 'init'
          tf_actions_working_dir: './terraform'
