name: Terraform
run-name: ${{ github.actor }} is running pre-commit

on:
  push:
    branches:
      - 13.0
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
